export enum SpeciesStatus {
  DATA_DEFICIENT = 'DD',
  LEAST_CONCERN = 'LC',
  NEAR_THREATENED = 'NT',
  VULNERABLE = 'VU',
  ENDANGERED = 'EN',
  CRITICALLY_ENDANGERED = 'CE',
  EXTINCT_WILD = 'EW',
  EXTINCT = 'EX',
  NOT_EVALUATED = 'NE',
}
